config/routes.rb
Clientcontacttest::Application.routes.draw do
  resources :order_statuses

  devise_for :users
  get "order_routing/index"
  get "order_routing/route_orders"
  resources :orders do
    collection do
      get 'select_sender_or_receiver', as: :select_srr
    end
  end

  resources :couriers
  
  resources :contact_types

  resources :clients do
    member do
      post 'select'
    end
  end

  root 'orders#index'

  

end

app/controllers/order_statuses_controller.rb
class OrderStatusesController < ApplicationController
  before_action :set_order_status, only: [:show, :edit, :update, :destroy]

  # GET /order_statuses
  # GET /order_statuses.json
  def index
    @order_statuses = OrderStatus.all
  end

  # GET /order_statuses/1
  # GET /order_statuses/1.json
  def show
  end

  # GET /order_statuses/new
  def new
    @order_status = OrderStatus.new
  end

  # GET /order_statuses/1/edit
  def edit
  end

  # POST /order_statuses
  # POST /order_statuses.json
  def create
    @order_status = OrderStatus.new(order_status_params)

    respond_to do |format|
      if @order_status.save
        format.html { redirect_to @order_status, notice: 'Order status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_statuses/1
  # PATCH/PUT /order_statuses/1.json
  def update
    respond_to do |format|
      if @order_status.update(order_status_params)
        format.html { redirect_to @order_status, notice: 'Order status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_statuses/1
  # DELETE /order_statuses/1.json
  def destroy
    @order_status.destroy
    respond_to do |format|
      format.html { redirect_to order_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_status
      @order_status = OrderStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_status_params
      params.require(:order_status).permit(:order_id, :courier_id, :date_planned, :comment)
    end
end

app/helpers/order_statuses_helper.rb
module OrderStatusesHelper
end

app/views/order_statuses/_form.html.erb
<%= simple_form_for @order_status, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  
  <%= f.association :order, label_method: :number, value_method: :id, input_html: { class: 'input-xlarge' } %>
  <%= f.association :courier, label_method: :full_name, value_method: :id, input_html: { class: 'input-xlarge' }  %>
  <%= f.input :date_planned, as: :string, input_html: { class: 'input-xlarge' }  %>
  <%= f.input :comment, input_html: { class: 'input-xlarge' }  %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                order_statuses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/order_statuses/edit.html.erb
<%- model_class = OrderStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/order_statuses/index.html.erb
<%- model_class = OrderStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:order_id) %></th>
      <th><%= model_class.human_attribute_name(:courier_id) %></th>
      <th><%= model_class.human_attribute_name(:date_planned) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @order_statuses.each do |order_status| %>
      <tr>
        <td><%= link_to order_status.id, order_status_path(order_status) %></td>
        <td><%= order_status.order_id %></td>
        <td><%= order_status.courier_id %></td>
        <td><%= order_status.date_planned %></td>
        <td><%= order_status.comment %></td>
        <td><%=l order_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_status_path(order_status), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_status_path(order_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_status_path,
            :class => 'btn btn-primary' %>

app/views/order_statuses/new.html.erb
<%- model_class = OrderStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/order_statuses/show.html.erb
<%- model_class = OrderStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @order_status.order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:courier_id) %>:</strong></dt>
  <dd><%= @order_status.courier_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_planned) %>:</strong></dt>
  <dd><%= @order_status.date_planned %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @order_status.comment %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              order_statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_status_path(@order_status), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_status_path(@order_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>