config/routes.rb
Clientcontacttest::Application.routes.draw do
  resources :order_statuses

  devise_for :users
  get "order_routing/index"
  get "order_routing/route_orders"
  resources :orders do
    collection do
      get 'select_sender_or_receiver', as: :select_srr
    end
  end

  resources :couriers
  
  resources :contact_types

  resources :clients do
    member do
      post 'select'
    end
  end

  root 'orders#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  
  include Filterable
  
  after_initialize :create_associated, :if => :new_record?
  after_destroy :destroy_address

  has_many :contacts, dependent: :destroy
  accepts_nested_attributes_for :contacts, :reject_if => :all_blank, allow_destroy: true

  belongs_to :address
  accepts_nested_attributes_for :address,  :reject_if => :all_blank, update_only: true
  
  has_many :sended_orders, :class_name => Order, :foreign_key => :sender_id
  has_many :received_orders, :class_name => Order, :foreign_key => :receiver_id
  
  validates :last_name, presence: true
  validates :first_name, :patronymic, presence: false, if: Proc.new { |client| !client.is_person }
  
  validates :address, presence: true
  
  scope :by_is_person,  -> isp   { where("is_person = ?", (isp == 0 ? false : true)) }
  scope :by_last_name,  -> lname { where("last_name LIKE ?", lname) }
  scope :by_first_name, -> fname { where("first_name LIKE ?", fname) }
  scope :by_patronymic, -> patr  { where("patronymic LIKE ?", patr) }
  scope :by_address_str, -> addr { includes(:address).where("addresses.city LIKE ? OR addresses.street LIKE ?", addr, addr) }

  def full_name
    last_name + ' ' + (first_name.nil? ? '' : first_name) + ' ' + (patronymic.nil? ? '' : patronymic)
  end


  def create_associated
    self.contacts.build if self.contacts.empty?
    self.build_address unless self.address
  end

  def destroy_address
    self.address.destroy if self.address
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :read_contact_types, only: [:new, :edit]

  # GET /clients
  # GET /clients.json
  def index
    #for making a parameter if a checkbox is not checked
    ip = index_params
    if ip[:is_person].nil? && !ip[:commit].nil?
      ip[:is_person] = 0
    end
    
    @clients = Client.includes(:address).filter(ip.slice(:is_person, :last_name, :first_name, :patronymic, :address_str)).paginate(:page => params[:page], :per_page => 5)
    
    @return_url = get_session_value(:return_url) || nil
  end
  
  #POST /clients/select_client
  def select
    redirect_url = get_session_value(:return_url).to_s
    #sr = get_session_value(:sr)
    client_id = params[:id].to_i
    if Client.exists?(client_id)
      if get_session_value(:srflag) == :sender
        set_session_value(:sender, client_id)
      else
	set_session_value(:receiver, client_id)
      end
      set_session_value(:return_url, nil)
      redirect_to redirect_url
      return
    else
      flash[:error] = "Wrong client chosen"
      redirect_to index
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    #reading contact types to use them in dropdown
    def read_contact_types
      @contact_types = ContactType.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:last_name, :first_name, :patronymic, :is_person, address_attributes: [:id, :city, :street, :building, :apartment], contacts_attributes: [:id, :contact_type_id, :value, :_destroy])
    end
    
    #strong_params for index filtering
    def index_params
      params.permit(:is_person, :last_name, :first_name, :patronymic, :address_str, :commit)
    end
    
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients_list.html.erb
<%- model_class = Client 
    clients = model
-%>
<table class = "table table-bordered table-striped">
  <thead>
    <tr>
      <% if !return_url.nil? %>
      <th>Select</th>
      <% end %>
      <th><%= model_class.human_attribute_name(:full_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% clients.each do |client| %>
      <tr>
        <% if !return_url.nil? %>
        <td>
          <%= link_to 'Select', select_client_path(client.id), :method=> :post %>
        </td>
        <% end %>
        <td><%= client.full_name %></td>
        <td><%= client.address.full_address_rus %></td>
        <td>
          <%= render "table_actions", model: client %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table> 

<%= link_to t('.new', :default => t("helpers.links.new")),
    new_client_path,
    class: 'btn btn-primary pull-right' %>

app/views/clients/_clients_sidebar.html.erb
<%= form_tag clients_path, method: 'get', class:'form-inline' do %>
  <div class='control-group'>
    <%= label_tag :is_person, nil, class: 'checkbox-inline' do %>
      <%= check_box_tag :is_person, 1, !params[:is_person].nil? %>
      <%= t('activerecord.attributes.client.is_person') %>
    <% end %>
  </div>
  
  <div class="control-group">
    <%= label_tag :last_name, t('activerecord.attributes.client.last_name') %>
    <div class="controls">
      <%= text_field_tag :last_name, params[:last_name] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag :first_name, t('activerecord.attributes.client.first_name') %>
    <div class="controls">
      <%= text_field_tag :first_name, params[:first_name] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag :patronymic, t('activerecord.attributes.client.patronymic') %>
    <div class="controls">
      <%= text_field_tag :patronymic, params[:patronymic] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag :patronymic, t('activerecord.attributes.client.address') %>
    <div class="controls">
      <%= text_field_tag :address_str, params[:address_str] %>
    </div>
  </div>
  
  <%= submit_tag t('filter'), class: 'btn btn-normal' %>
  <%= link_to t('clear'), orders_path, class: 'btn btn-normal' %>
<% end %>

app/views/clients/_form.html.erb
<%= simple_form_for @client, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/client_fields', f: f %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, class: 'btn' %>
  </div>
<% end %>

app/views/clients/_map_client.html.erb
<script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>

<%= content_tag :div, class: "address_data", data: {address: client} do %>
<% end %>

<div id="map" style="width: 100%; height: 400px"></div>

<script type="text/javascript">
    ymaps.ready(init);
    var myMap;

    function init(){
	    
	    var lat = $('.address_data').data('address').latitude;
	    var lng = $('.address_data').data('address').longitude;
	    var address = 'ул. ' + $('.address_data').data('address').street + ' д. ' + $('.address_data').data('address').building + ' кв. ' + $('.address_data').data('address').apartment;

            myMap = new ymaps.Map('map', {
                center: [lat, lng],
                zoom : 12
            });

            var clientGeoObject = new ymaps.Placemark([lat, lng], {balloonContent: address});
//             clientGeoObject = new ymaps.GeoObject({
//               geometry: {
//                 type: "Point",// тип геометрии - точка
//                 coordinates: [lat, lng] // координаты точки
//               }
//             });
            myMap.geoObjects.add(clientGeoObject);
    }
</script> 

app/views/clients/_show_contacts.html.erb
<table class = "table table-bordered">
  <thead>
    <tr>
      <th><%= Contact.human_attribute_name(:contact_type) %></th>
      <th><%= Contact.human_attribute_name(:value) %></th>
    </tr>
  </thead>

  <tbody>
    <% contacts.each do |c| %>
      <tr>
        <td><%= c.contact_type.type_name %></td>
        <td><%= c.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>  

app/views/clients/edit.html.erb
<h1>
  <%= t '.title' %>
  <%= link_to @client, class: 'btn' do %>
    <i class="icon-eye-open"></i> <%= t('.show', :default => t("helpers.links.show")) %>
  <% end %>
</h1>

<%= render 'form' %>

app/views/clients/index.html.erb
<%= render "universal_index_partial", model: @clients, table_locals: { model: @clients, return_url: @return_url }, sidebar_title: t('filter') %>

app/views/clients/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row-fluid">
<div class="span4">
<dl class="dl-horizontal">
  <dt><strong><%= @client.is_person ? model_class.human_attribute_name(:last_name) : model_class.human_attribute_name(:name_not_person) %>:</strong></dt>
  <dd><%= @client.last_name %></dd>
</dl>
<% if @client.is_person %>
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
    <dd><%= @client.first_name %></dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:patronymic) %>:</strong></dt>
    <dd><%= @client.patronymic %></dd>
  </dl>
<% end %>
<h5> <b><%= t('activerecord.attributes.client.address') %></b> </h5>
<%= render "shared/show_address", address: @client.address %>

<%= render 'show_contacts', contacts: @client.contacts %>

</div>

<div class="span8">

<%= render "map_client", client: @client.address %>

</div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              clients_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_client_path(@client), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              client_path(@client),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>