config/routes.rb
Clientcontacttest::Application.routes.draw do
  resources :order_statuses

  devise_for :users
  get "order_routing/index"
  get "order_routing/route_orders"
  resources :orders do
    collection do
      get 'select_sender_or_receiver', as: :select_srr
    end
  end

  resources :couriers
  
  resources :contact_types

  resources :clients do
    member do
      post 'select'
    end
  end

  root 'orders#index'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  #for filtering:
  include Filterable
  
  belongs_to :sender,   :class_name => Client
  belongs_to :receiver, :class_name => Client
  
  has_many :order_statuses
  
  before_create :set_dates
  after_create :set_number
  
  validates :sender_id, :receiver_id, presence: true
  #taken from stackoverflow
  validates :sum, :format => { :with => /\A\d+??(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0, :less_than => 1000000}
  
  #scopes
  scope :by_issue_date_start, -> date_beg { where("issued_date >= ?", date_beg) }
  scope :by_issue_date_end, -> date_end { where("issued_date <= ?", date_end) }
  scope :by_delivery_date_start, -> date_beg { where("delivered_date >= ?", date_beg) }
  scope :by_delivery_date_end, -> date_end { where("delivered_date<= ?", date_end) }
  scope :by_sender, -> sender_id { where("sender_id = ?", sender_id) }
  scope :by_receiver, -> receiver_id { where("receiver_id = ?", receiver_id) }
  scope :by_number, -> number { where("number = ?", number) }
  
  def is_delivered?
    return self.delivered_date < DateTime.current
  end
  
  private
  
  def set_dates
    self.issued_date = DateTime.current
    self.delivered_date = Date.new(2099, 01, 01)
  end
  
  def set_number
    self.number = self.id + 10000
    self.save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController  
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :load_sender_and_receiver, only: [:new, :edit]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.includes(:sender, :receiver).filter(index_params.slice(:number, :issue_date_start, :issue_date_end, :delivery_date_start, :delivery_date_end)).paginate(:page => params[:page], :per_page => 15)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
	clear_session_client_values
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  
  def select_sender_or_receiver
    if srr_params[:srflag].nil? || request.referer.nil?
      raise ActionController::RoutingError.new('Not Found')
    end
    set_session_value(:return_url, URI(request.referer).path) #need to make this more modern!
    #Rails::logger.debug params[:srflag].inspect
    set_session_value(:srflag, srr_params[:srflag].to_sym)
    redirect_to clients_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:sender_id, :receiver_id, :sum, :delivered_date)
    end
    
    def index_params
      params.permit(:number, :issue_date_start, :issue_date_end, :delivery_date_start, :delivery_date_end, :sender_id, :receiver_id)
    end
    
    def srr_params
      params.permit(:srflag)
    end
    
    def load_sender_and_receiver
      sender_id = get_session_value(:sender)
      if sender_id 
	@sender = Client.find(sender_id)
      end
      
      receiver_id = get_session_value(:receiver)
      if receiver_id 
	@receiver = Client.find(receiver_id)
      end
    end
    
    def clear_session_client_values
      set_session_value(:sender, nil)
      set_session_value(:receiver, nil)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for @order, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <div class="control-group">
    <%= f.label :sender %>
    <div class="controls">
      <%= render partial: "select_client", locals: { local_object: @sender, model_object: @order.sender, target: :sender, f: f } %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver %>
    <div class="controls">
      <%= render partial: "select_client", locals: { local_object: @receiver, model_object: @order.receiver, target: :receiver, f: f } %>
    </div>
  </div>
  
  <%= f.input :sum %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn' %>
  </div>
<% end %>

app/views/orders/_orders_list.html.erb
<%- model_class = Order 
    orders = model
-%>
<%= form_tag orders_path, method: 'get', class: 'form-inline' do %>
  <div class="form-group">
    <%= label_tag model_class.human_attribute_name(:number) %>
    <%= text_field_tag :number, params[:number], class: 'search-query' %>

    <%= submit_tag 'Search', class: 'btn btn-normal' %>
    <%= link_to 'Clear', orders_path, class: 'btn btn-normal' %>
  </div>
<% end %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:sender_id) %></th>
      <th><%= model_class.human_attribute_name(:receiver_id) %></th>
      <th><%= model_class.human_attribute_name(:sum) %></th>
      <th><%= model_class.human_attribute_name(:delivered_date) %></th>
      <th><%= model_class.human_attribute_name(:issued_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= order.number %></td>
        <td><%= order.sender.full_name %></td>
        <td><%= order.receiver.full_name %></td>
        <td><%= order.sum %></td>
        <td>
	  <% if order.delivered_date <= Date.today %>
	    <%= l order.delivered_date, format: :long %>
	  <% else %>
	    <%= t('activerecord.attributes.order.not_delivered') %>
	  <% end %>
	</td>
        <td><%= l order.issued_date, format: :long %></td>
        <td>
          <%= render "table_actions", model: order %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_path,
            :class => 'btn btn-primary' %>
 

app/views/orders/_orders_sidebar.html.erb
<%= form_tag orders_path, method: 'get', :class => 'form-inline' do %>  
  <div class="control-group">
    <%= label_tag t 'orders.sidebar.issue_date_start' %>
    <div class="controls">
      <%= text_field_tag :issue_date_start, params[:issue_date_start] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag t 'orders.sidebar.issue_date_end' %>
    <div class="controls">
      <%= text_field_tag :issue_date_end, params[:issue_date_end] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag t 'orders.sidebar.delivery_date_start' %>
    <div class="controls">
      <%= text_field_tag :delivery_date_start, params[:delivery_date_start] %>
    </div>
  </div>
  
  <div class="control-group">
    <%= label_tag t 'orders.sidebar.delivery_date_end' %>
    <div class="controls">
      <%= text_field_tag :delivery_date_end, params[:delivery_date_end] %>
    </div>
  </div>
  
  <%= submit_tag t('filter'), class: 'btn btn-normal' %>
  <%= link_to t('clear'), orders_path, class: 'btn btn-normal' %>
<% end %>

<!--<script type='text/javascript' >
  $('input[id^=date]').datepicker();
</script> -->

app/views/orders/_select_client.html.erb
<% obj = local_object.nil?  ? model_object : local_object %>
<div class="input-append">
  <% unless obj.nil? %>
  <span class="input uneditable-input"> <%= obj.full_name %> </span>
  <%= f.hidden_field(target.to_s + '_id', :value => obj.id) %>
  <% end %>
  <%= link_to '...', select_srr_orders_path(:srflag => target), class: 'btn' %>
</div>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%= render "universal_index_partial", model: @orders, table_locals: { model: @orders }, sidebar_title: t('filter')  %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @order.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sender_id) %>:</strong></dt>
  <dd><%= @order.sender_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_id) %>:</strong></dt>
  <dd><%= @order.receiver_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sum) %>:</strong></dt>
  <dd><%= @order.sum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:delivered_date) %>:</strong></dt>
  <dd><%= @order.delivered_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:issued_date) %>:</strong></dt>
  <dd><%= @order.issued_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>